name = "Meow Boing Squish"
author = "copygirl, lizzie, Lyra"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3835393756d0748a254bf0d28e49b185336935a90da032a88e4b2e08b90864fe"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
