name = "Meow Boing Squish"
author = "copygirl, lizzie, Lyra"
version = "0.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b081b7ce3196957689a7bdbb4be66353152d2ba3e4aea52efd1394881615323"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
