name = "Meow Boing Squish"
author = "copygirl, lizzie, Lyra"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed57d518c1c1aed7a908fcf0157ed3d06e2a23ad547413309f23fc1963313c33"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
