name = "Meow Boing Squish"
author = "copygirl, lizzie, Lyra"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9c83afb45692d7ee60a4cd60224f949570d04ae8d291bbb11d951385a6abcd5"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
