name = "Meow Boing Squish"
author = "copygirl, lizzie, Lyra"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d7c4ced8fde240eb4c5e4c294b17bb6df97ce7747b3aaf2687c8233bd193007"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
