name = "Meow Boing Squish"
author = "copygirl, lizzie, Lyra"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dacb2dd1be2b334850a25910b09786442f046e13dcc3a29d2d825b7e05d599a"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
