"Allow all items to be added" = false
"Whitelisted Items" = [
    "ars_nouveau:worn_notebook",
    "assemblylinemachines:guidebook",
    "essentials:guide_book",
    "occultism:dictionary_of_spirits",
    "patchouli:guide_book",
    "tis3d:manual"
]
"Whitelisted Names" = []
"Blacklisted Mods" = []
"Mod Aliases" = []
