name = "Alternate Current"
filename = "alternate-current-mc1.18-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3602/373/alternate-current-mc1.18-1.1.0.jar"
hash-format = "sha1"
hash = "b481cd04409179aa83d24063e49535f4d5c60daa"

[update]
[update.curseforge]
file-id = 3602373
project-id = 548115
