name = "Assembly Line Machines"
filename = "assemblylinemachines-1.18.1-1.3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/609/assemblylinemachines-1.18.1-1.3.8.jar"
hash-format = "sha1"
hash = "243239684986e29dcc1971476c61d75469973779"

[update]
[update.curseforge]
file-id = 3623609
project-id = 388282
