name = "Blueprint"
filename = "blueprint-1.18.1-5.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/224/blueprint-1.18.1-5.1.1.jar"
hash-format = "sha1"
hash = "eb14800dbbebd80fdbc5baa17b693f225913ca2a"

[update]
[update.curseforge]
file-id = 3645224
project-id = 382216
