name = "Champions"
filename = "champions-forge-1.18.2-2.1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3694/134/champions-forge-1.18.2-2.1.1.0.jar"
hash-format = "sha1"
hash = "72679bccadc279961f937b81e3e10691f6b388d1"

[update]
[update.curseforge]
file-id = 3694134
project-id = 307152
