name = "Compat O' Plenty"
filename = "Compat-O-Plenty-1.18.1-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/761/Compat-O-Plenty-1.18.1-1.4.2.jar"
hash-format = "sha1"
hash = "08c3007f97a594279713364de6bcff066a25d371"

[update]
[update.curseforge]
file-id = 3671761
project-id = 558850
