name = "Compact Machines"
filename = "compactmachines-4.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3695/916/compactmachines-4.1.0.jar"
hash-format = "sha1"
hash = "d61947679f5fb8174e05cff8930f7b643e29f3c5"

[update]
[update.curseforge]
file-id = 3695916
project-id = 224218
