name = "Controllable"
filename = "controllable-0.15.1-1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3546/297/controllable-0.15.1-1.18.jar"
hash-format = "sha1"
hash = "71669851a7744007e125ce554eb58131c04b6934"

[update]
[update.curseforge]
file-id = 3546297
project-id = 317269

[option]
description = "Use a controller to play Minecraft"
optional = true
default = false
