name = "Corn Delight"
filename = "corn_delight-1.0.6-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3694/576/corn_delight-1.0.6-1.18.1.jar"
hash-format = "sha1"
hash = "9310d1b8f0128c2ad24620c5f9b8cbc1b71e9f4f"

[update]
[update.curseforge]
file-id = 3694576
project-id = 577805
