name = "Corn Delight"
filename = "corn_delight-1.0.5-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3676/34/corn_delight-1.0.5-1.18.1.jar"
hash-format = "sha1"
hash = "f1c0043b949082ff8e497e20abe2efbaf09006db"

[update]
[update.curseforge]
file-id = 3676034
project-id = 577805
