name = "Create"
filename = "create-mc1.18.1_v0.4f.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3706/700/create-mc1.18.1_v0.4f.jar"
hash-format = "sha1"
hash = "cf1ff9a94fecb09e027a7cfc298bf24ddd413c22"

[update]
[update.curseforge]
file-id = 3706700
project-id = 328085
