name = "Cyclops Core"
filename = "CyclopsCore-1.18.1-1.13.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3614/854/CyclopsCore-1.18.1-1.13.0.jar"
hash-format = "sha1"
hash = "6006d4031d470317c3024acba7bace782a7d4638"

[update]
[update.curseforge]
file-id = 3614854
project-id = 232758
