name = "Cyclops Core"
filename = "CyclopsCore-1.18.1-1.13.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3694/468/CyclopsCore-1.18.1-1.13.2.jar"
hash-format = "sha1"
hash = "aee3217597a7f8a73175c9f54610766f258f1ca3"

[update]
[update.curseforge]
file-id = 3694468
project-id = 232758
