name = "Cyclops Core"
filename = "CyclopsCore-1.18.1-1.13.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/831/CyclopsCore-1.18.1-1.13.1.jar"
hash-format = "sha1"
hash = "c1eb5478a5046e1952966c5321776db9a84176a9"

[update]
[update.curseforge]
file-id = 3683831
project-id = 232758
