name = "Enchanting Overhauled"
filename = "enchanting_overhauled-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/864/enchanting_overhauled-1.0.5.jar"
hash-format = "sha1"
hash = "3cb11a69a314070def76e7e27641fa65d1182d03"

[update]
[update.curseforge]
file-id = 3670864
project-id = 565463
