name = "Engineer's Decor"
filename = "engineersdecor-1.18.1-1.1.19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3653/113/engineersdecor-1.18.1-1.1.19.jar"
hash-format = "sha1"
hash = "4c274e8e206742ae47da117ac9e61a67f0102a5d"

[update]
[update.curseforge]
file-id = 3653113
project-id = 313866
