name = "Enigmatic Legacy"
filename = "EnigmaticLegacy-2.17.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/951/EnigmaticLegacy-2.17.3.jar"
hash-format = "sha1"
hash = "cc648a550e886069cfa9d9be3485b12141bea5bd"

[update]
[update.curseforge]
file-id = 3668951
project-id = 336184
