name = "Farmer's Delight"
filename = "FarmersDelight-1.18.1-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/366/FarmersDelight-1.18.1-1.0.3.jar"
hash-format = "sha1"
hash = "654d5d76c6a1032e6c8496e8ca83de6b4083785d"

[update]
[update.curseforge]
file-id = 3615366
project-id = 398521
