name = "FastSuite"
filename = "FastSuite-1.18.1-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3567/88/FastSuite-1.18.1-3.0.0.jar"
hash-format = "sha1"
hash = "64926cc95d83f99bae93b4c87eba253833652fe4"

[update]
[update.curseforge]
file-id = 3567088
project-id = 475117
