name = "First-person Model (Forge/Fabric)"
filename = "firstperson-forge-2.1.0-mc1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3556/530/firstperson-forge-2.1.0-mc1.18.jar"
hash-format = "sha1"
hash = "5ad6b3dd8840169ee48d1dcec882e5067fee5996"

[update]
[update.curseforge]
file-id = 3556530
project-id = 333287

[option]
description = "See your model in first-person (togglable)"
optional = true
default = true
