name = "Flywheel"
filename = "flywheel-forge-1.18-0.6.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3687/357/flywheel-forge-1.18-0.6.1.jar"
hash-format = "sha1"
hash = "f7b4edf9ff0a4e00976c48b1bb650328f7d753ac"

[update]
[update.curseforge]
file-id = 3687357
project-id = 486392
