name = "Flywheel"
filename = "flywheel-forge-1.18-0.6.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3623/314/flywheel-forge-1.18-0.6.0.jar"
hash-format = "sha1"
hash = "db37868e3e27d9a960b7e8bbb742d3c78b58ca83"

[update]
[update.curseforge]
file-id = 3623314
project-id = 486392
