name = "Integrated Terminals"
filename = "IntegratedTerminals-1.18.1-1.2.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3694/517/IntegratedTerminals-1.18.1-1.2.16.jar"
hash-format = "sha1"
hash = "0f0c429814d2f09221f1ba4774e1c8c77ca9783d"

[update]
[update.curseforge]
file-id = 3694517
project-id = 295910
