name = "Integrated Dynamics"
filename = "IntegratedDynamics-1.18.1-1.10.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/774/IntegratedDynamics-1.18.1-1.10.11.jar"
hash-format = "sha1"
hash = "4b27350fbc596806d7b6d6d525efb720b11bb524"

[update]
[update.curseforge]
file-id = 3684774
project-id = 236307
