name = "Integrated Terminals"
filename = "IntegratedTerminals-1.18.1-1.2.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/970/IntegratedTerminals-1.18.1-1.2.15.jar"
hash-format = "sha1"
hash = "ca045c380b09246a35526e28fce39569d0f65b0d"

[update]
[update.curseforge]
file-id = 3669970
project-id = 295910
