name = "Inventory Hotswap"
filename = "inventoryhotswap-1.18.1-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/292/inventoryhotswap-1.18.1-1.3.jar"
hash-format = "sha1"
hash = "36decd5a822005c6671d85f6315617cf4b7818a8"

[update]
[update.curseforge]
file-id = 3590292
project-id = 423235

[option]
description = "Easily swap items in hotbar with one above it in the same column"
optional = true
default = false
