name = "KubeJS Create"
filename = "kubejs-create-1801.2.0-build.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3584/653/kubejs-create-1801.2.0-build.14.jar"
hash-format = "sha1"
hash = "8dfbb2ab6c4816cedf1ca1950e5a46ea8904750a"

[update]
[update.curseforge]
file-id = 3584653
project-id = 429371
