name = "Legendary Tooltips"
filename = "LegendaryTooltips-1.18.1-1.2.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3653/194/LegendaryTooltips-1.18.1-1.2.4.jar"
hash-format = "sha1"
hash = "321aa9b56f7e50d01922c0b7bff7cea22b860230"

[update]
[update.curseforge]
file-id = 3653194
project-id = 532127
