name = "LibX"
filename = "LibX-1.18.1-3.1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/631/LibX-1.18.1-3.1.18.jar"
hash-format = "sha1"
hash = "fd813cb886a4e5d35a230d6eef55c301e371a438"

[update]
[update.curseforge]
file-id = 3667631
project-id = 412525
