name = "Lootr"
filename = "lootr-1.18-0.1.15.50.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/675/lootr-1.18-0.1.15.50.jar"
hash-format = "sha1"
hash = "35d1fae28bba07f048195a2fcdfd7467082aff58"

[update]
[update.curseforge]
file-id = 3672675
project-id = 361276
