name = "Mahou Tsukai"
filename = "mahoutsukai-1.18.1-v1.34.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3659/546/mahoutsukai-1.18.1-v1.34.8.jar"
hash-format = "sha1"
hash = "3d9803b1b4a807919e1e8e8e57bddef7819e1759"

[update]
[update.curseforge]
file-id = 3659546
project-id = 342543
