name = "Mysterious Mountain Lib"
filename = "mmlib-1.0.0-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3642/415/mmlib-1.0.0-1.18.1.jar"
hash-format = "sha1"
hash = "3adad54bcc483714ee5ad64fd8d68cc8f0526f75"

[update]
[update.curseforge]
file-id = 3642415
project-id = 368098
