name = "Not Enough Animations"
filename = "notenoughanimations-forge-1.4.0-mc1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3548/349/notenoughanimations-forge-1.4.0-mc1.18.jar"
hash-format = "sha1"
hash = "939110f5d2bca24815bd8f17bf94a29bc99efc1c"

[update]
[update.curseforge]
file-id = 3548349
project-id = 433760
