name = "Pick Up Notifier [Forge]"
filename = "PickUpNotifier-v3.1.0-1.18.1-Forge.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3570/56/PickUpNotifier-v3.1.0-1.18.1-Forge.jar"
hash-format = "sha1"
hash = "394a59a87e3418fffb2de234488a46e1f8bcc308"

[update]
[update.curseforge]
file-id = 3570056
project-id = 351441
