name = "Regrowth"
filename = "Regrowth-1.18.1-1.39.0.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3635/468/Regrowth-1.18.1-1.39.0.26.jar"
hash-format = "sha1"
hash = "fff0aae9c2c9806bdc6ad5497df75a43c7011cd1"

[update]
[update.curseforge]
file-id = 3635468
project-id = 381597
