name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-4.2.11+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/485/repurposed_structures_forge-4.2.11+1.18.1.jar"
hash-format = "sha1"
hash = "cdb4d21060987c8edec0193aa42900c979fbe9fa"

[update]
[update.curseforge]
file-id = 3649485
project-id = 368293
