name = "Rhino"
filename = "rhino-forge-1801.1.8-build.108.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3711/803/rhino-forge-1801.1.8-build.108.jar"
hash-format = "sha1"
hash = "f7b12855c9ab89b5453d4ef1ec7eae1e0d5790a4"

[update]
[update.curseforge]
file-id = 3711803
project-id = 416294
