name = "Selene Lib"
filename = "selene-1.18-1.13.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/969/selene-1.18-1.13.2.jar"
hash-format = "sha1"
hash = "e1fe924e4217599611a17ce8e49aac1a65f05838"

[update]
[update.curseforge]
file-id = 3668969
project-id = 499980
