name = "Sophisticated Backpacks"
filename = "sophisticatedbackpacks-1.18.1-3.15.15.550.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3693/291/sophisticatedbackpacks-1.18.1-3.15.15.550.jar"
hash-format = "sha1"
hash = "64ed43d3034306a1c6a1b7c755e92d671e88bb0c"

[update]
[update.curseforge]
file-id = 3693291
project-id = 422301
