name = "Sophisticated Backpacks"
filename = "sophisticatedbackpacks-1.18.1-3.15.9.533.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3640/344/sophisticatedbackpacks-1.18.1-3.15.9.533.jar"
hash-format = "sha1"
hash = "dc562739a3ac50a5a055f8e15023e1cf0c2a5f15"

[update]
[update.curseforge]
file-id = 3640344
project-id = 422301
