name = "Tax Free Levels (Fabric/Forge)"
filename = "TaxFreeLevels-1.3.1-forge-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/838/TaxFreeLevels-1.3.1-forge-1.18.1.jar"
hash-format = "sha1"
hash = "4a6a13936d44a71d115888bbcfaa5a88bace8229"

[update]
[update.curseforge]
file-id = 3631838
project-id = 462128
