name = "TerraBlender (Forge)"
filename = "TerraBlender-forge-1.18.1-1.1.0.77.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/452/TerraBlender-forge-1.18.1-1.1.0.77.jar"
hash-format = "sha1"
hash = "03d11fc0522e43d87f532df3d1347f3dc6cdfbe7"

[update]
[update.curseforge]
file-id = 3651452
project-id = 563928
