name = "Tetra"
filename = "tetra-1.18.1-4.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/819/tetra-1.18.1-4.8.0.jar"
hash-format = "sha1"
hash = "b0a3116c5bdb7dac7a75c3e770c51eb64db54759"

[update]
[update.curseforge]
file-id = 3666819
project-id = 289712
