name = "Time in a bottle standalone"
filename = "time-in-a-bottle-2.1.0-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3565/298/time-in-a-bottle-2.1.0-mc1.18.1.jar"
hash-format = "sha1"
hash = "75481f0016057a365c458c9a0fcf769362cb7e1b"

[update]
[update.curseforge]
file-id = 3565298
project-id = 445025
