name = "TimeoutFixes"
filename = "timeout_fixes-1.18.1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/293/timeout_fixes-1.18.1-1.0.0.jar"
hash-format = "sha1"
hash = "a8653c72d892dbcfa7bb14e6e4bf90a9086c38f3"

[update]
[update.curseforge]
file-id = 3570293
project-id = 558010
