name = "Tiny Gates"
filename = "tinygates-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3544/668/tinygates-2.0.0.jar"
hash-format = "sha1"
hash = "4d9a275edeb8d4a1f4aea2dcb173a9dabaf122b4"

[update]
[update.curseforge]
file-id = 3544668
project-id = 522875
