name = "Ultimate Plane Mod"
filename = "plane-1.18.1-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3687/779/plane-1.18.1-1.0.1.jar"
hash-format = "sha1"
hash = "b19553e11fbd4e0abc0522aaf8e2762e3390fcf6"

[update]
[update.curseforge]
file-id = 3687779
project-id = 414049
