name = "When Dungeons Arise - Forge!"
filename = "DungeonsArise-1.18.1-2.1.49d-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3632/92/DungeonsArise-1.18.1-2.1.49d-beta.jar"
hash-format = "sha1"
hash = "1f229e74a707a46098b5d0510af3a271c43979a5"

[update]
[update.curseforge]
file-id = 3632092
project-id = 442508
