name = "WTHIT Forge Edition"
filename = "wthit-forge-4.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/4/wthit-forge-4.5.5.jar"
hash-format = "sha1"
hash = "e01e5d0f5370291dafb6fe08846da713e679ea8b"

[update]
[update.curseforge]
file-id = 3707004
project-id = 455982
