name = "WTHIT Forge Edition"
filename = "wthit-forge-4.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/799/wthit-forge-4.5.4.jar"
hash-format = "sha1"
hash = "91e23a26c7f7dc119a8d0364053f8d282fdc5508"

[update]
[update.curseforge]
file-id = 3662799
project-id = 455982
