name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.3.1_Forge_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/989/XaerosWorldMap_1.20.3.1_Forge_1.18.jar"
hash-format = "sha1"
hash = "730754507b920601a58abf5835444f9ef3b291b5"

[update]
[update.curseforge]
file-id = 3646989
project-id = 317780
