name = "YUNG's Better Strongholds (Forge)"
filename = "BetterStrongholds-Forge-1.18.1-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/543/BetterStrongholds-Forge-1.18.1-1.0.2.jar"
hash-format = "sha1"
hash = "27a468842e68c95810e03b931ae237225febe023"

[update]
[update.curseforge]
file-id = 3652543
project-id = 465575
