name = "YUNG's Bridges (Forge)"
filename = "YungsBridges-Forge-1.18.1-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/409/YungsBridges-Forge-1.18.1-1.0.jar"
hash-format = "sha1"
hash = "f96025e6f4e4eb12a65abc193e281bdfde6c21c0"

[update]
[update.curseforge]
file-id = 3681409
project-id = 536660
