name = "YUNG's API (Forge)"
filename = "YungsApi-1.18.1-Forge-26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/394/YungsApi-1.18.1-Forge-26.jar"
hash-format = "sha1"
hash = "3a980ab64eb5c6fcaec4b6a0d83b5b2abfa9283b"

[update]
[update.curseforge]
file-id = 3681394
project-id = 421850
